class Constants:
    VIDEO_DEFAULT_IMAGE_SIZE: int
    VIDEO_IMAGE_EXTRACTION_INTERVAL: int
    VIDEO_DEFAULT_PLUG_PYAV: str
    FUNC_NAME_FOR_STRUCTURED_OUTPUT: str
    DEFAULT_TOP_K_RESULTS: int
    DEFAULT_SIMILARITY_THRESHOLD: float
