from _typeshed import Incomplete
from camel.agents import ChatAgent
from camel.models import BaseModelBackend as BaseModelBackend
from camel.responses import ChatAgentResponse

logger: Incomplete
SYS_MSG_CONTENT: str
TOOLS_PROMPT: str
FINAL_RESPONSE_PROMPT: str

class MCPAgent(ChatAgent):
    def __init__(self, config_path: str, model: BaseModelBackend | None = None, function_calling_available: bool = False) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    def add_mcp_tools(self) -> None: ...
    async def run(self, prompt: str) -> ChatAgentResponse: ...
    @classmethod
    async def create(cls, config_path: str, model: BaseModelBackend | None = None, function_calling_available: bool = False) -> MCPAgent: ...
