from camel.agents.chat_agent import ChatAgent
from camel.models import BaseModelBackend as BaseModelBackend

class SearchAgent(ChatAgent):
    def __init__(self, model: BaseModelBackend | None = None) -> None: ...
    def summarize_text(self, text: str, query: str) -> str: ...
    def continue_search(self, query: str, answer: str) -> bool: ...
