from _typeshed import Incomplete
from apify_client.clients import DatasetClient

class Apify:
    client: Incomplete
    def __init__(self, api_key: str | None = None) -> None: ...
    def run_actor(self, actor_id: str, run_input: dict | None = None, content_type: str | None = None, build: str | None = None, max_items: int | None = None, memory_mbytes: int | None = None, timeout_secs: int | None = None, webhooks: list | None = None, wait_secs: int | None = None) -> dict | None: ...
    def get_dataset_client(self, dataset_id: str) -> DatasetClient: ...
    def get_dataset(self, dataset_id: str) -> dict | None: ...
    def update_dataset(self, dataset_id: str, name: str) -> dict: ...
    def get_dataset_items(self, dataset_id: str) -> list: ...
    def get_datasets(self, unnamed: bool | None = None, limit: int | None = None, offset: int | None = None, desc: bool | None = None) -> list[dict]: ...
