from _typeshed import Incomplete
from pydantic import BaseModel
from typing import Any

logger: Incomplete

class Crawl4AI:
    crawler_class: Incomplete
    def __init__(self) -> None: ...
    async def crawl(self, start_url: str, max_depth: int = 1, extraction_strategy=None, **kwargs) -> list[dict[str, Any]]: ...
    async def scrape(self, url: str, extraction_strategy=None, **kwargs) -> dict[str, Any]: ...
    async def structured_scrape(self, url: str, response_format: BaseModel, api_key: str | None = None, llm_provider: str = 'ollama/llama3', **kwargs) -> Any: ...
    async def map_site(self, start_url: str, **kwargs) -> list[str]: ...
