from _typeshed import Incomplete
from pydantic import BaseModel
from typing import Any

class Firecrawl:
    app: Incomplete
    def __init__(self, api_key: str | None = None, api_url: str | None = None) -> None: ...
    def crawl(self, url: str, params: dict[str, Any] | None = None, **kwargs: Any) -> Any: ...
    def check_crawl_job(self, job_id: str) -> dict: ...
    def scrape(self, url: str, params: dict[str, Any] | None = None) -> dict: ...
    def structured_scrape(self, url: str, response_format: BaseModel) -> dict: ...
    def map_site(self, url: str, params: dict[str, Any] | None = None) -> list: ...
