from _typeshed import Incomplete

class MinerU:
    is_ocr: Incomplete
    enable_formula: Incomplete
    enable_table: Incomplete
    layout_model: Incomplete
    language: Incomplete
    def __init__(self, api_key: str | None = None, api_url: str | None = 'https://mineru.net/api/v4', is_ocr: bool = False, enable_formula: bool = False, enable_table: bool = True, layout_model: str = 'doclayout_yolo', language: str = 'en') -> None: ...
    def extract_url(self, url: str) -> dict: ...
    def batch_extract_urls(self, files: list[dict[str, str | bool]]) -> str: ...
    def get_task_status(self, task_id: str) -> dict: ...
    def get_batch_status(self, batch_id: str) -> dict: ...
    def wait_for_completion(self, task_id: str, is_batch: bool = False, timeout: float = 100, check_interval: float = 5) -> dict: ...
