from _typeshed import Incomplete
from typing import Any

class ScrapeGraphAI:
    client: Incomplete
    def __init__(self, api_key: str | None = None) -> None: ...
    def search(self, user_prompt: str) -> dict[str, Any]: ...
    def scrape(self, website_url: str, user_prompt: str, website_html: str | None = None) -> dict[str, Any]: ...
    def close(self) -> None: ...
