from camel.storages.key_value_storages import BaseKeyValueStorage
from typing import Any

class InMemoryKeyValueStorage(BaseKeyValueStorage):
    memory_list: list[dict]
    def __init__(self) -> None: ...
    def save(self, records: list[dict[str, Any]]) -> None: ...
    def load(self) -> list[dict[str, Any]]: ...
    def clear(self) -> None: ...
