from camel.types import ModelType as ModelType

class UnifiedModelType(str):
    def __new__(cls, value: ModelType | str) -> UnifiedModelType: ...
    def __init__(self, value: ModelType | str) -> None: ...
    @property
    def value_for_tiktoken(self) -> str: ...
    @property
    def token_limit(self) -> int: ...
    @property
    def is_openai(self) -> bool: ...
    @property
    def is_aws_bedrock(self) -> bool: ...
    @property
    def is_anthropic(self) -> bool: ...
    @property
    def is_azure_openai(self) -> bool: ...
    @property
    def is_groq(self) -> bool: ...
    @property
    def is_openrouter(self) -> bool: ...
    @property
    def is_lmstudio(self) -> bool: ...
    @property
    def is_ppio(self) -> bool: ...
    @property
    def is_zhipuai(self) -> bool: ...
    @property
    def is_gemini(self) -> bool: ...
    @property
    def is_mistral(self) -> bool: ...
    @property
    def is_netmind(self) -> bool: ...
    @property
    def is_reka(self) -> bool: ...
    @property
    def is_cohere(self) -> bool: ...
    @property
    def is_yi(self) -> bool: ...
    @property
    def is_qwen(self) -> bool: ...
    @property
    def is_internlm(self) -> bool: ...
    @property
    def is_modelscope(self) -> bool: ...
    @property
    def is_moonshot(self) -> bool: ...
    @property
    def is_novita(self) -> bool: ...
    @property
    def is_watsonx(self) -> bool: ...
    @property
    def support_native_structured_output(self) -> bool: ...
    @property
    def support_native_tool_calling(self) -> bool: ...
