from camel.toolkits.base import BaseToolkit
from camel.toolkits.function_tool import FunctionTool

class MathToolkit(BaseToolkit):
    def add(self, a: float, b: float) -> float: ...
    def sub(self, a: float, b: float) -> float: ...
    def multiply(self, a: float, b: float, decimal_places: int = 2) -> float: ...
    def divide(self, a: float, b: float, decimal_places: int = 2) -> float: ...
    def round(self, a: float, decimal_places: int = 0) -> float: ...
    def get_tools(self) -> list[FunctionTool]: ...
