from _typeshed import Incomplete
from camel.agents import ChatAgent
from camel.toolkits.base import BaseToolkit
from camel.toolkits.function_tool import FunctionTool

class MemoryToolkit(BaseToolkit):
    agent: Incomplete
    def __init__(self, agent: ChatAgent, timeout: float | None = None) -> None: ...
    def save(self, path: str) -> str: ...
    def load(self, memory_json: str) -> str: ...
    def load_from_path(self, path: str) -> str: ...
    def clear_memory(self) -> str: ...
    def get_tools(self) -> list[FunctionTool]: ...
