from camel.toolkits import FunctionTool
from typing import Any, Callable

class OpenAPIToolkit:
    def parse_openapi_file(self, openapi_spec_path: str) -> dict[str, Any] | None: ...
    def openapi_spec_to_openai_schemas(self, api_name: str, openapi_spec: dict[str, Any]) -> list[dict[str, Any]]: ...
    def openapi_function_decorator(self, api_name: str, base_url: str, path: str, method: str, openapi_security: list[dict[str, Any]], sec_schemas: dict[str, dict[str, Any]], operation: dict[str, Any]) -> Callable: ...
    def generate_openapi_funcs(self, api_name: str, openapi_spec: dict[str, Any]) -> list[Callable]: ...
    def apinames_filepaths_to_funs_schemas(self, apinames_filepaths: list[tuple[str, str]]) -> tuple[list[Callable], list[dict[str, Any]]]: ...
    def generate_apinames_filepaths(self) -> list[tuple[str, str]]: ...
    def get_tools(self) -> list[FunctionTool]: ...
