from camel.toolkits import BaseToolkit, FunctionTool as FunctionTool

class PlaywrightMCPToolkit(BaseToolkit):
    def __init__(self, timeout: float | None = None) -> None: ...
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    def get_tools(self) -> list[FunctionTool]: ...
