from _typeshed import Incomplete
from camel.toolkits import BaseToolkit, FunctionTool
from typing import Literal

logger: Incomplete
DURATION: float

class PyAutoGUIToolkit(BaseToolkit):
    pyautogui: Incomplete
    safe_margin: float
    safe_min_x: Incomplete
    safe_max_x: Incomplete
    safe_min_y: Incomplete
    safe_max_y: Incomplete
    screen_center: Incomplete
    screenshots_dir: Incomplete
    def __init__(self, timeout: float | None = None, screenshots_dir: str = 'tmp') -> None: ...
    def mouse_move(self, x: int, y: int) -> str: ...
    def mouse_click(self, button: Literal['left', 'middle', 'right'] = 'left', clicks: int = 1, x: int | None = None, y: int | None = None) -> str: ...
    def get_mouse_position(self) -> str: ...
    def take_screenshot(self) -> str: ...
    def mouse_drag(self, start_x: int, start_y: int, end_x: int, end_y: int, button: Literal['left', 'middle', 'right'] = 'left') -> str: ...
    def scroll(self, scroll_amount: int, x: int | None = None, y: int | None = None) -> str: ...
    def keyboard_type(self, text: str, interval: float = 0.0) -> str: ...
    def press_key(self, key: str | list[str]) -> str: ...
    def hotkey(self, keys: list[str]) -> str: ...
    def get_tools(self) -> list[FunctionTool]: ...
