from _typeshed import Incomplete
from camel.toolkits import FunctionTool
from camel.toolkits.base import BaseToolkit

logger: Incomplete

class ThinkingToolkit(BaseToolkit):
    plans: list[str]
    hypotheses: list[str]
    thoughts: list[str]
    contemplations: list[str]
    critiques: list[str]
    syntheses: list[str]
    reflections: list[str]
    def __init__(self, timeout: float | None = None) -> None: ...
    def plan(self, plan: str) -> str: ...
    def hypothesize(self, hypothesis: str) -> str: ...
    def think(self, thought: str) -> str: ...
    def contemplate(self, contemplation: str) -> str: ...
    def critique(self, critique: str) -> str: ...
    def synthesize(self, synthesis: str) -> str: ...
    def reflect(self, reflection: str) -> str: ...
    def get_tools(self) -> list[FunctionTool]: ...
