from _typeshed import Incomplete
from abc import ABC
from camel.societies.workforce.base import BaseNode
from camel.societies.workforce.task_channel import TaskChannel

logger: Incomplete

class Worker(BaseNode, ABC):
    def __init__(self, description: str) -> None: ...
    def set_channel(self, channel: TaskChannel): ...
    async def start(self) -> None: ...
    def stop(self) -> None: ...
