from _typeshed import Incomplete
from camel.memories.base import MemoryBlock
from camel.memories.records import ContextRecord, MemoryRecord
from camel.storages.key_value_storages.base import BaseKeyValueStorage as BaseKeyValueStorage

class ChatHistoryBlock(MemoryBlock):
    storage: Incomplete
    keep_rate: Incomplete
    def __init__(self, storage: BaseKeyValueStorage | None = None, keep_rate: float = 0.9) -> None: ...
    def retrieve(self, window_size: int | None = None) -> list[ContextRecord]: ...
    def write_records(self, records: list[MemoryRecord]) -> None: ...
    def clear(self) -> None: ...
