from _typeshed import Incomplete
from camel.agents.tool_agents.base import BaseToolAgent
from typing import Any

class HuggingFaceToolAgent(BaseToolAgent):
    agent_image_type: Incomplete
    agent: Incomplete
    remote: Incomplete
    def __init__(self, name: str, *args: Any, remote: bool = True, **kwargs: Any) -> None: ...
    def reset(self) -> None: ...
    def step(self, *args: Any, remote: bool | None = None, **kwargs: Any) -> Any: ...
    def chat(self, *args: Any, remote: bool | None = None, **kwargs: Any) -> Any: ...
